import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
import mejiLogo from '../public/meji_logo.webp';
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col p-24">
          <div className="flex items-center gap-4 border-b-2 border-black mb-16 pb-4">
            <Link href={'/'}>
              <Image
                src={mejiLogo}
                width="150"
                height="150"
                alt="Meji"
              />
            </Link>
            <span className="font-bold text-4xl">codingskills</span>
            <span className="font-bold text-4xl text-blue-500">PLAY</span>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
